// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyRungPhongHo.Data;

#nullable disable

namespace QuanLyRungPhongHo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219145316_InitialCreate_Clean")]
    partial class InitialCreate_Clean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucThon", b =>
                {
                    b.Property<string>("MaThon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMucXaMaXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThon");

                    b.HasIndex("DanhMucXaMaXa");

                    b.ToTable("DanhMucThons");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucXa", b =>
                {
                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenXa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaXa");

                    b.ToTable("DanhMucXas");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.LoRung", b =>
                {
                    b.Property<int>("MaLo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLo"));

                    b.Property<string>("DanhMucThonMaThon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiRung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaThon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoKhoanh")
                        .HasColumnType("int");

                    b.Property<int?>("SoLo")
                        .HasColumnType("int");

                    b.Property<int?>("SoTieuKhu")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLo");

                    b.HasIndex("DanhMucThonMaThon");

                    b.ToTable("LoRungs");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhanSu", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanhMucXaMaXa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("DanhMucXaMaXa");

                    b.ToTable("NhanSus");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhatKyBaoVe", b =>
                {
                    b.Property<int>("MaNK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNK"));

                    b.Property<int?>("LoRungMaLo")
                        .HasColumnType("int");

                    b.Property<string>("LoaiSuViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLo")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV_GhiNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanSuMaNV")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToaDoGPS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNK");

                    b.HasIndex("LoRungMaLo");

                    b.HasIndex("NhanSuMaNV");

                    b.ToTable("NhatKyBaoVes");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.SinhVat", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSV"));

                    b.Property<int?>("LoRungMaLo")
                        .HasColumnType("int");

                    b.Property<string>("LoaiSV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLo")
                        .HasColumnType("int");

                    b.Property<string>("MucDoQuyHiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSV");

                    b.HasIndex("LoRungMaLo");

                    b.ToTable("SinhVats");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaTK");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucThon", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.DanhMucXa", "DanhMucXa")
                        .WithMany("DanhMucThons")
                        .HasForeignKey("DanhMucXaMaXa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucXa");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.LoRung", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.DanhMucThon", "DanhMucThon")
                        .WithMany("LoRungs")
                        .HasForeignKey("DanhMucThonMaThon");

                    b.Navigation("DanhMucThon");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhanSu", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.DanhMucXa", "DanhMucXa")
                        .WithMany("NhanSus")
                        .HasForeignKey("DanhMucXaMaXa");

                    b.Navigation("DanhMucXa");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhatKyBaoVe", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.LoRung", "LoRung")
                        .WithMany("NhatKyBaoVes")
                        .HasForeignKey("LoRungMaLo");

                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NhanSu")
                        .WithMany("NhatKyBaoVes")
                        .HasForeignKey("NhanSuMaNV");

                    b.Navigation("LoRung");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.SinhVat", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.LoRung", "LoRung")
                        .WithMany("SinhVats")
                        .HasForeignKey("LoRungMaLo");

                    b.Navigation("LoRung");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NhanSu")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyRungPhongHo.Models.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucThon", b =>
                {
                    b.Navigation("LoRungs");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucXa", b =>
                {
                    b.Navigation("DanhMucThons");

                    b.Navigation("NhanSus");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.LoRung", b =>
                {
                    b.Navigation("NhatKyBaoVes");

                    b.Navigation("SinhVats");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhanSu", b =>
                {
                    b.Navigation("NhatKyBaoVes");

                    b.Navigation("TaiKhoan");
                });
#pragma warning restore 612, 618
        }
    }
}
