// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyRungPhongHo.Data;

#nullable disable

namespace QuanLyRungPhongHo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203155915_AddWorkScheduleManagement")]
    partial class AddWorkScheduleManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLRungPhongHo.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time(7)");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time(7)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaCa");

                    b.ToTable("CaLamViecs");

                    b.HasData(
                        new
                        {
                            MaCa = 1,
                            GioBatDau = new TimeSpan(0, 7, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 11, 0, 0, 0),
                            MoTa = "Ca làm việc buổi sáng",
                            TenCa = "Ca Sáng",
                            TrangThai = true
                        },
                        new
                        {
                            MaCa = 2,
                            GioBatDau = new TimeSpan(0, 13, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 17, 0, 0, 0),
                            MoTa = "Ca làm việc buổi chiều",
                            TenCa = "Ca Chiều",
                            TrangThai = true
                        },
                        new
                        {
                            MaCa = 3,
                            GioBatDau = new TimeSpan(0, 18, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 22, 0, 0, 0),
                            MoTa = "Ca làm việc buổi tối",
                            TenCa = "Ca Tối",
                            TrangThai = true
                        },
                        new
                        {
                            MaCa = 4,
                            GioBatDau = new TimeSpan(0, 8, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 17, 0, 0, 0),
                            MoTa = "Ca hành chính cả ngày",
                            TenCa = "Ca Hành Chính",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("QLRungPhongHo.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChamCong"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime?>("GioVao")
                        .HasColumnType("datetime2(7)");

                    b.Property<int>("MaLich")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoGioLam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ToaDoGPS_Ra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToaDoGPS_Vao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChamCong");

                    b.HasIndex("MaLich")
                        .IsUnique();

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.DonXinNghi", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNghi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("NguoiDuyet")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDon");

                    b.HasIndex("MaNV");

                    b.HasIndex("NguoiDuyet");

                    b.ToTable("DonXinNghis");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<int?>("MaLo")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(7)");

                    b.Property<DateTime>("NgayLamViec")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2(7)");

                    b.Property<int?>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLich");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaLo");

                    b.HasIndex("NguoiTao");

                    b.HasIndex("MaNV", "NgayLamViec")
                        .IsUnique();

                    b.ToTable("LichLamViecs");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.NgayNghiLe", b =>
                {
                    b.Property<int>("MaNgayNghi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNgayNghi"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNgayNghi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("TenNgayNghi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaNgayNghi");

                    b.ToTable("NgayNghiLes");

                    b.HasData(
                        new
                        {
                            MaNgayNghi = 1,
                            LoaiNgayNghi = "Tết",
                            NgayBatDau = new DateTime(2026, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenNgayNghi = "Tết Nguyên Đán 2026"
                        },
                        new
                        {
                            MaNgayNghi = 2,
                            LoaiNgayNghi = "Lễ",
                            NgayBatDau = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenNgayNghi = "Giỗ Tổ Hùng Vương"
                        },
                        new
                        {
                            MaNgayNghi = 3,
                            LoaiNgayNghi = "Lễ",
                            NgayBatDau = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenNgayNghi = "Ngày Giải phóng miền Nam"
                        },
                        new
                        {
                            MaNgayNghi = 4,
                            LoaiNgayNghi = "Lễ",
                            NgayBatDau = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenNgayNghi = "Ngày Quốc tế Lao động"
                        },
                        new
                        {
                            MaNgayNghi = 5,
                            LoaiNgayNghi = "Lễ",
                            NgayBatDau = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NgayKetThuc = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenNgayNghi = "Quốc Khánh"
                        });
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucThon", b =>
                {
                    b.Property<string>("MaThon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaXa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenThon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaThon");

                    b.HasIndex("MaXa");

                    b.ToTable("DanhMucThons");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucXa", b =>
                {
                    b.Property<string>("MaXa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenXa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaXa");

                    b.ToTable("DanhMucXas");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.LoRung", b =>
                {
                    b.Property<int>("MaLo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLo"));

                    b.Property<decimal?>("DienTich")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiRung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaThon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SoKhoanh")
                        .HasColumnType("int");

                    b.Property<int?>("SoLo")
                        .HasColumnType("int");

                    b.Property<int?>("SoTieuKhu")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLo");

                    b.HasIndex("MaThon");

                    b.ToTable("LoRungs");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhanSu", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaXa")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaXa");

                    b.ToTable("NhanSus");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhatKyBaoVe", b =>
                {
                    b.Property<int>("MaNK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNK"));

                    b.Property<string>("LoaiSuViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLo")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV_GhiNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToaDoGPS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNK");

                    b.HasIndex("MaLo");

                    b.HasIndex("MaNV_GhiNhan");

                    b.ToTable("NhatKyBaoVes");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleName", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTK");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("SinhVat", b =>
                {
                    b.Property<int>("MaSV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSV"));

                    b.Property<string>("LoaiSV")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaLo")
                        .HasColumnType("int");

                    b.Property<string>("MucDoQuyHiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLo");

                    b.ToTable("SinhVats");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.ChamCong", b =>
                {
                    b.HasOne("QLRungPhongHo.Models.LichLamViec", "LichLamViec")
                        .WithOne("ChamCong")
                        .HasForeignKey("QLRungPhongHo.Models.ChamCong", "MaLich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichLamViec");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.DonXinNghi", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NguoiDuyetDon")
                        .WithMany()
                        .HasForeignKey("NguoiDuyet")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NguoiDuyetDon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.LichLamViec", b =>
                {
                    b.HasOne("QLRungPhongHo.Models.CaLamViec", "CaLamViec")
                        .WithMany("LichLamViecs")
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyRungPhongHo.Models.LoRung", "LoRung")
                        .WithMany()
                        .HasForeignKey("MaLo");

                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NguoiTaoLich")
                        .WithMany()
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CaLamViec");

                    b.Navigation("LoRung");

                    b.Navigation("NguoiTaoLich");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucThon", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.DanhMucXa", "DanhMucXa")
                        .WithMany("DanhMucThons")
                        .HasForeignKey("MaXa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucXa");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.LoRung", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.DanhMucThon", "DanhMucThon")
                        .WithMany("LoRungs")
                        .HasForeignKey("MaThon")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DanhMucThon");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhanSu", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.DanhMucXa", "DanhMucXa")
                        .WithMany("NhanSus")
                        .HasForeignKey("MaXa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DanhMucXa");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhatKyBaoVe", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.LoRung", "LoRung")
                        .WithMany("NhatKyBaoVes")
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NhanSu")
                        .WithMany("NhatKyBaoVes")
                        .HasForeignKey("MaNV_GhiNhan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LoRung");

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.RolePermission", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.TaiKhoan", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.NhanSu", "NhanSu")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("QuanLyRungPhongHo.Models.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanSu");
                });

            modelBuilder.Entity("SinhVat", b =>
                {
                    b.HasOne("QuanLyRungPhongHo.Models.LoRung", "LoRung")
                        .WithMany("SinhVats")
                        .HasForeignKey("MaLo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("LoRung");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.CaLamViec", b =>
                {
                    b.Navigation("LichLamViecs");
                });

            modelBuilder.Entity("QLRungPhongHo.Models.LichLamViec", b =>
                {
                    b.Navigation("ChamCong");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucThon", b =>
                {
                    b.Navigation("LoRungs");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.DanhMucXa", b =>
                {
                    b.Navigation("DanhMucThons");

                    b.Navigation("NhanSus");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.LoRung", b =>
                {
                    b.Navigation("NhatKyBaoVes");

                    b.Navigation("SinhVats");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.NhanSu", b =>
                {
                    b.Navigation("NhatKyBaoVes");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyRungPhongHo.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
